config/routes.rb
Rails.application.routes.draw do
	root 'application#index'
	resources :cars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  validates :model, :color, length: { in: 3..40 }
  validates :destination, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index; end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
	def index
		@cars = Car.all
	end

	def new
		@car = Car.new
	end

	def show
		@car = resource
	end

	def edit
		@car = resource
	end

	def create
    @car = Car.new(car_params)
    if @car.save
      flash[:success] = "Have a nice journey!"
      redirect_to car_path(@car)
    else
      flash.now[:error] = "Something went wrong!"
      render :new
    end
  end

  def update
    @car = resource
    if @car.update(car_params)
      flash[:success] = "The problem is fixed!"
      redirect_to cars_path
    else
      flash.now[:error] = "Something went wrong!"
      render :edit
    end
  end

  def destroy
    @car = resource
    @car.destroy

    redirect_to cars_path, notice: 'Successfully deleted.'
  end

  private

  def resource
  	Car.find(params[:id])
  end

	def car_params
    params.require(:car).permit(:model, :color, :destination)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/views/application/index.html.erb
<div class="m-auto" id="welcome-block">
  <h1>
    Glad to see you!
  </h1>
  <h1>
  	Our journey  will be wonderful!
  </h1>
  <div class="form-group text-center">
    <button class="btn btn-success btn-lg">
      <%= link_to "Let's go!", new_car_path %>
    </button>
  </div>
</div>

app/views/cars/edit.html.erb
<%= render 'shared/flash' %>
<div class="container col-md-8 pt-3">
  <h2 class="font-weight-bold text-center pt-5">
    Something wrong with the trip?
  </h2>
  <%= render 'shared/form' %>
</div>

app/views/cars/index.html.erb
<%= render 'shared/flash' %>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col" width="300">Car model</th>
      <th scope="col">Car color</th>
      <th scope="col">Destination</th>
      <th colspan="3" width=25%>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @cars.each do |car| %>
    <tr>
      <td>
        <%= car.model %>
      </td>
      <td>
        <%= car.color %>
      </td>
      <td>
        <%= car.destination %>
      </td>
      <td>
        <%= link_to "Show", car_path(car) %>
      </td>
      <td>
        <%= link_to "Edit", edit_car_path(car) %>
      </td>
      <td>
        <%= link_to "Delete", car_path(car), method: :delete, data: {confirm: "Are you sure?"} %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="form-group text-center">
  <button class="btn btn-success btn-lg">
    <% if Car.count == 0 %>
      <%= link_to "Do you want to travel?", new_car_path %>
    <% else %>
      <%= link_to "Another journey?", new_car_path %>
    <% end %>
  </button>
</div>

app/views/cars/new.html.erb
<%= render 'shared/flash' %>
<div class="container col-md-8 pt-3">
  <h2 class="font-weight-bold text-center pt-5">
    Where are you going?
  </h2>
  <%= render 'shared/form' %>
</div>

app/views/cars/show.html.erb
<%= render 'shared/flash' %>
<div class="m-auto" id="welcome-block">
  <h1>Today, I'm going to take my <%= @car.color %> <%= @car.model %> and go to <%= @car.destination %>!
  </h1>
  <div class="form-group text-center">
    <div class="btn btn-secondary btn-lg">
      <%= link_to "See what places I've visited", cars_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show">
    <%= msg %>
    <button class="close" data-dismiss="alert"></button>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= simple_form_for @car do |f| %>
<div class="form-group">
  <div class="row">
    <div class="col-md-6">
      <%= f.input :model, class: 'form-control', placeholder: "Сar model", label: false %>
    </div>
    <div class="col-md-6">
      <%= f.input :color, class: 'form-control', placeholder: "Сolor of the car", label: false %>
    </div>
  </div>
</div>
<div class="form-group">
  <%= f.input :destination, class: 'form-control', placeholder: "Destination", label: false %>
</div>
<div class="form-group text-center">
  <div class="btn btn-secondary btn-lg">
    <%= link_to "Cancel", cars_path %>
  </div>
  <%= f.button :submit, "Let's go!", class: "btn btn-success btn-lg" %>
</div>
<% end %>